/**
 * 시드 데이터: 한국 대학 정보 (Wikidata SPARQL 기반)
 *
 * 출처: Wikidata (https://query.wikidata.org)
 * 총 183개 대학, API 키 없이 즉시 사용 가능
 * 지역, 웹사이트, 유형, 설립 구분 포함
 */

import type { PublicUniversityInfo } from './types'

export const KOREAN_UNIVERSITIES: PublicUniversityInfo[] = [
  { schoolName: '가톨릭관동대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.cku.ac.kr/' },
  { schoolName: '가톨릭꽃동네대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.kkot.ac.kr/' },
  { schoolName: '강동대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.gangdong.ac.kr/' },
  { schoolName: '강릉영동대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.gyc.ac.kr/' },
  { schoolName: '강원관광대학교', schoolType: '대학', establishType: '사립', region: '' },
  { schoolName: '거제대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.koje.ac.kr/' },
  { schoolName: '건동대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.kundong.ac.kr/' },
  { schoolName: '건양사이버대학교', schoolType: '사이버대학', establishType: '사립', region: '', website: 'https://www.kycu.ac.kr/kor.do' },
  { schoolName: '경기대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.kyonggi.ac.kr/' },
  { schoolName: '경남과학기술대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.gntech.ac.kr/' },
  { schoolName: '경북과학대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.kbsu.ac.kr/' },
  { schoolName: '경북전문대학교', schoolType: '전문대학', establishType: '사립', region: '', website: 'http://www.kbc.ac.kr/' },
  { schoolName: '계원예술대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.kaywon.ac.kr' },
  { schoolName: '고려사이버대학교', schoolType: '사이버대학', establishType: '사립', region: '', website: 'http://www.cuk.edu/' },
  { schoolName: '광주가톨릭대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.gjcatholic.ac.kr/' },
  { schoolName: '광주여자대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.kwu.ac.kr/' },
  { schoolName: '국립경국대학교', schoolType: '대학', establishType: '국립', region: '', website: 'http://www.andong.ac.kr/' },
  { schoolName: '군산대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.kunsan.ac.kr/' },
  { schoolName: '금강대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.ggu.ac.kr' },
  { schoolName: '김천과학대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.gch.ac.kr' },
  { schoolName: '김천대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.gimcheon.ac.kr/new_web/language/english/main/main.php' },
  { schoolName: '김해대학교', schoolType: '대학', establishType: '사립', region: '' },
  { schoolName: '대구가톨릭대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://global.cu.ac.kr' },
  { schoolName: '대구교육대학교', schoolType: '교육대학', establishType: '국립', region: '', website: 'http://www.dnue.ac.kr/' },
  { schoolName: '대신대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.daeshin.ac.kr/html/00_main/' },
  { schoolName: '대전대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.dju.ac.kr/' },
  { schoolName: '대전신학대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.daejeon.ac.kr/' },
  { schoolName: '대진대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.daejin.ac.kr/' },
  { schoolName: '동신대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.dsu.ac.kr/cms/' },
  { schoolName: '동아보건대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.dongac.ac.kr' },
  { schoolName: '동양대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.dyu.ac.kr/' },
  { schoolName: '동원과학기술대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.dist.ac.kr/main.do' },
  { schoolName: '두원공과대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.doowon.ac.kr/html/_en/main/main.html' },
  { schoolName: '문경대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.mkc.ac.kr' },
  { schoolName: '부천대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.bc.ac.kr/' },
  { schoolName: '서울디지털대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.sdu.ac.kr' },
  { schoolName: '서정대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.seojeong.ac.kr/' },
  { schoolName: '성결대학교', schoolType: '대학', establishType: '사립', region: '' },
  { schoolName: '세명대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.semyung.ac.kr/' },
  { schoolName: '세한대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.sehan.ac.kr/main/main.do' },
  { schoolName: '수원과학대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.ssc.ac.kr/' },
  { schoolName: '수원대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.suwon.ac.kr' },
  { schoolName: '신성대학교', schoolType: '대학', establishType: '사립', region: '' },
  { schoolName: '신안산대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.sau.ac.kr' },
  { schoolName: '신흥대학교', schoolType: '대학', establishType: '사립', region: '' },
  { schoolName: '안산대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.ansan.ac.kr' },
  { schoolName: '연성대학교', schoolType: '대학', establishType: '사립', region: '' },
  { schoolName: '연암공과대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.yc.ac.kr' },
  { schoolName: '연암대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.yonam.ac.kr/' },
  { schoolName: '예원예술대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.yewon.ac.kr/' },
  { schoolName: '오산대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.osan.ac.kr/' },
  { schoolName: '위덕대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.uu.ac.kr/' },
  { schoolName: '유한대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.yuhan.ac.kr/en/enterInfo/ei1001.jsp' },
  { schoolName: '전북과학대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.jbsc.ac.kr/' },
  { schoolName: '중부대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.joongbu.ac.kr/' },
  { schoolName: '진주교육대학교', schoolType: '교육대학', establishType: '국립', region: '', website: 'http://www.cue.ac.kr/' },
  { schoolName: '청주교육대학교', schoolType: '교육대학', establishType: '국립', region: '', website: 'https://www.cje.ac.kr' },
  { schoolName: '청주대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.cju.ac.kr/' },
  { schoolName: '초당대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.chodang.ac.kr/' },
  { schoolName: '충북대학교', schoolType: '대학', establishType: '국립', region: '', website: 'https://www.cbnu.ac.kr/' },
  { schoolName: '충청대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.ok.ac.kr' },
  { schoolName: '평택대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.ptu.ac.kr/' },
  { schoolName: '한국공학대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.tukorea.ac.kr/' },
  { schoolName: '한국교통대학교', schoolType: '대학', establishType: '국립', region: '', website: 'http://www.ut.ac.kr/' },
  { schoolName: '한국국제대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.iuk.ac.kr/' },
  { schoolName: '한국기술교육대학교', schoolType: '교육대학', establishType: '국립', region: '', website: 'http://www.koreatech.ac.kr' },
  { schoolName: '한국승강기대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.kcpc.ac.kr/' },
  { schoolName: '한국에너지공과대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.kentech.ac.kr/' },
  { schoolName: '한국전통문화대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://nuch.ac.kr' },
  { schoolName: '한국정보통신기능대학', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.ict.ac.kr/eng' },
  { schoolName: '한국폴리텍VI대학', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.dgpc.ac.kr/' },
  { schoolName: '한동대학교', schoolType: '대학', establishType: '사립', region: '', website: 'https://www.handong.edu' },
  { schoolName: '한서대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.hanseo.ac.kr' },
  { schoolName: '한신대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.hs.ac.kr/' },
  { schoolName: '한일장신대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.hanil.ac.kr/eng/' },
  { schoolName: '호남대학교', schoolType: '대학', establishType: '사립', region: '', website: 'http://www.honam.ac.kr/' },
  { schoolName: '춘천교육대학교', schoolType: '교육대학', establishType: '국립', region: '강원', website: 'http://www.cnue.ac.kr/' },
  { schoolName: '한라대학교', schoolType: '대학', establishType: '사립', region: '강원', website: 'http://www.halla.ac.kr/' },
  { schoolName: '한림대학교', schoolType: '대학', establishType: '사립', region: '강원', website: 'http://www.hallym.ac.kr' },
  { schoolName: '한림성심대학교', schoolType: '대학', establishType: '사립', region: '강원', website: 'http://www.hsc.ac.kr/site/hsc/main.do' },
  { schoolName: '강남대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://www.kangnam.ac.kr' },
  { schoolName: '국제사이버대학교', schoolType: '사이버대학', establishType: '사립', region: '경기' },
  { schoolName: '대림대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://www.daelim.ac.kr' },
  { schoolName: '루터대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://www.ltu.ac.kr' },
  { schoolName: '신구대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://www.shingu.ac.kr' },
  { schoolName: '아주대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://www.ajou.ac.kr/' },
  { schoolName: '용인대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://www.yongin.ac.kr' },
  { schoolName: '용인예술과학대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://english.ysc.ac.kr/' },
  { schoolName: '한국항공대학교', schoolType: '대학', establishType: '사립', region: '경기', website: 'http://www.kau.ac.kr/english' },
  { schoolName: '경남대학교', schoolType: '대학', establishType: '사립', region: '경남', website: 'http://www.kyungnam.ac.kr/' },
  { schoolName: '마산대학교', schoolType: '대학', establishType: '사립', region: '경남' },
  { schoolName: '부산장신대학교', schoolType: '대학', establishType: '사립', region: '경남', website: 'http://www.bjc.ac.kr/' },
  { schoolName: '창원대학교', schoolType: '대학', establishType: '사립', region: '경남', website: 'http://www.changwon.ac.kr/' },
  { schoolName: '경운대학교', schoolType: '대학', establishType: '사립', region: '경북', website: 'http://www.ikw.ac.kr/eng/main/main.html' },
  { schoolName: '경일대학교', schoolType: '대학', establishType: '사립', region: '경북', website: 'http://eng.kiu.ac.kr/english/index.htm' },
  { schoolName: '대구외국어대학교', schoolType: '대학', establishType: '사립', region: '경북', website: 'http://www.dufs.ac.kr' },
  { schoolName: '아시아대학교', schoolType: '대학', establishType: '사립', region: '경북' },
  { schoolName: '영남신학대학교', schoolType: '대학', establishType: '사립', region: '경북', website: 'http://www.yntcs.ac.kr/' },
  { schoolName: '광신대학교', schoolType: '대학', establishType: '사립', region: '광주', website: 'http://www.kwangshin.ac.kr/' },
  { schoolName: '광주과학기술원', schoolType: '대학', establishType: '국립', region: '광주', website: 'https://www.gist.ac.kr/en/main.html' },
  { schoolName: '광주교육대학교', schoolType: '교육대학', establishType: '국립', region: '광주', website: 'http://eng.gnue.ac.kr/' },
  { schoolName: '광주대학교', schoolType: '대학', establishType: '사립', region: '광주', website: 'http://www.gwangju.ac.kr' },
  { schoolName: '기독간호대학교', schoolType: '대학', establishType: '사립', region: '광주', website: 'http://www.ccn.ac.kr' },
  { schoolName: '동원대학교', schoolType: '대학', establishType: '사립', region: '광주', website: 'http://www.tw.ac.kr' },
  { schoolName: '경북대학교', schoolType: '대학', establishType: '사립', region: '대구', website: 'http://www.knu.ac.kr/' },
  { schoolName: '대구경북과학기술원', schoolType: '대학', establishType: '국립', region: '대구', website: 'https://dgist.ac.kr/' },
  { schoolName: '대구공업대학교', schoolType: '대학', establishType: '사립', region: '대구', website: 'https://www.funttc.com/contents/main/main.aspx' },
  { schoolName: '대구대학 (1947년)', schoolType: '대학', establishType: '사립', region: '대구', website: 'https://eng.daegu.ac.kr/main' },
  { schoolName: '대구대학교', schoolType: '대학', establishType: '사립', region: '대구', website: 'http://daegu.ac.kr/' },
  { schoolName: '대구보건대학교', schoolType: '대학', establishType: '사립', region: '대구', website: 'http://www.dhc.ac.kr/' },
  { schoolName: '대구예술대학교', schoolType: '대학', establishType: '사립', region: '대구', website: 'http://www.dgau.ac.kr/' },
  { schoolName: '대구한의대학교', schoolType: '대학', establishType: '사립', region: '대구', website: 'http://www.dhu.ac.kr' },
  { schoolName: '영남대학교', schoolType: '대학', establishType: '사립', region: '대구', website: 'http://www.yu.ac.kr/' },
  { schoolName: '대덕대학교', schoolType: '대학', establishType: '사립', region: '대전', website: 'http://english.ddu.ac.kr' },
  { schoolName: '대전보건대학교', schoolType: '대학', establishType: '사립', region: '대전', website: 'http://www.hit.ac.kr' },
  { schoolName: '목원대학교', schoolType: '대학', establishType: '사립', region: '대전', website: 'http://www.mokwon.ac.kr/' },
  { schoolName: '우송대학교', schoolType: '대학', establishType: '사립', region: '대전', website: 'http://www.wsu.ac.kr/' },
  { schoolName: '을지대학교', schoolType: '대학', establishType: '사립', region: '대전', website: 'http://www.eu.ac.kr' },
  { schoolName: '한국과학기술원', schoolType: '대학', establishType: '국립', region: '대전', website: 'https://kaist.ac.kr' },
  { schoolName: '한국침례신학대학교', schoolType: '대학', establishType: '사립', region: '대전', website: 'http://www.kbtus.ac.kr' },
  { schoolName: '한밭대학교', schoolType: '대학', establishType: '국립', region: '대전', website: 'http://www.hanbat.ac.kr/html/en/' },
  { schoolName: '경성대학교', schoolType: '대학', establishType: '사립', region: '부산', website: 'http://ks.ac.kr/' },
  { schoolName: '고신대학교', schoolType: '대학', establishType: '사립', region: '부산', website: 'https://www.kosin.ac.kr' },
  { schoolName: '동명대학교', schoolType: '대학', establishType: '사립', region: '부산', website: 'http://english.tu.ac.kr/default/new/main.jsp' },
  { schoolName: '동서대학교', schoolType: '대학', establishType: '사립', region: '부산', website: 'http://uni.dongseo.ac.kr/eng/' },
  { schoolName: '부산가톨릭대학교', schoolType: '대학', establishType: '사립', region: '부산', website: 'http://www.cup.ac.kr/' },
  { schoolName: '부산대학교', schoolType: '대학', establishType: '사립', region: '부산', website: 'http://www.pusan.ac.kr/' },
  { schoolName: '영산대학교', schoolType: '대학', establishType: '사립', region: '부산', website: 'http://www.ysu.ac.kr/' },
  { schoolName: '영진전문대학교', schoolType: '전문대학', establishType: '사립', region: '부산', website: 'http://www.yju.ac.kr/' },
  { schoolName: '한국해양대학교', schoolType: '대학', establishType: '국립', region: '부산', website: 'http://www.kmou.ac.kr' },
  { schoolName: '가톨릭대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.cuk.ac.kr/' },
  { schoolName: '감리교신학대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://mtu.ac.kr' },
  { schoolName: '경희사이버대학교', schoolType: '사이버대학', establishType: '사립', region: '서울' },
  { schoolName: '국방대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'https://www.kndu.ac.kr/' },
  { schoolName: '극동대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.kdu.ac.kr/' },
  { schoolName: '동양미래대학교', schoolType: '대학', establishType: '사립', region: '서울' },
  { schoolName: '백석예술대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.baekseokart.ac.kr/' },
  { schoolName: '삼육대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.syu.ac.kr/' },
  { schoolName: '상명대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.smu.ac.kr' },
  { schoolName: '서강대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.sogang.ac.kr/' },
  { schoolName: '서울과학기술대학교', schoolType: '대학', establishType: '국립', region: '서울', website: 'http://www.seoultech.ac.kr/' },
  { schoolName: '서울교육대학교', schoolType: '교육대학', establishType: '국립', region: '서울', website: 'http://www.snue.ac.kr/' },
  { schoolName: '서울기독대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.scu.ac.kr' },
  { schoolName: '서울시립대학교', schoolType: '대학', establishType: '국립', region: '서울', website: 'http://www.uos.ac.kr' },
  { schoolName: '서울신학대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.stu.ac.kr/' },
  { schoolName: '서울여자간호대학', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.snjc.ac.kr/' },
  { schoolName: '서울예술대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'https://www.seoularts.ac.kr' },
  { schoolName: '성공회대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'https://chn.skhu.ac.kr/chn/index.do' },
  { schoolName: '성신여자대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.sungshin.ac.kr/' },
  { schoolName: '숭의여자대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.sewc.ac.kr/' },
  { schoolName: '인덕대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.induk.ac.kr/en/index.asp' },
  { schoolName: '추계예술대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.chugye.ac.kr/' },
  { schoolName: '한국방송통신대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.knou.ac.kr/' },
  { schoolName: '한국예술종합학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.knua.ac.kr' },
  { schoolName: '한국외국어대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'https://hufsenglish.hufs.ac.kr/' },
  { schoolName: '한세대학교', schoolType: '대학', establishType: '사립', region: '서울', website: 'http://www.hansei.ac.kr' },
  { schoolName: '한양사이버대학교', schoolType: '사이버대학', establishType: '사립', region: '서울', website: 'http://en.hycu.ac.kr/' },
  { schoolName: '고려대학교 세종캠퍼스', schoolType: '대학', establishType: '사립', region: '세종', website: 'https://sejong.korea.ac.kr/chi' },
  { schoolName: '대전가톨릭대학교', schoolType: '대학', establishType: '사립', region: '세종', website: 'http://www.dcatholic.ac.kr/' },
  { schoolName: '울산과학기술원', schoolType: '대학', establishType: '국립', region: '울산', website: 'http://www.unist.ac.kr/' },
  { schoolName: '울산대학교', schoolType: '대학', establishType: '사립', region: '울산', website: 'http://www.ulsan.ac.kr' },
  { schoolName: '경인교육대학교', schoolType: '교육대학', establishType: '국립', region: '인천', website: 'http://www.ginue.ac.kr/' },
  { schoolName: '인천대학교', schoolType: '대학', establishType: '국립', region: '인천', website: 'https://www.inu.ac.kr/' },
  { schoolName: '인천재능대학교', schoolType: '대학', establishType: '사립', region: '인천', website: 'http://www.jeiu.ac.kr/' },
  { schoolName: '명신대학교', schoolType: '대학', establishType: '사립', region: '전남', website: 'http://www.myungshin.ac.kr' },
  { schoolName: '목포가톨릭대학교', schoolType: '대학', establishType: '사립', region: '전남', website: 'https://www.mcu.ac.kr' },
  { schoolName: '목포대학교', schoolType: '대학', establishType: '사립', region: '전남', website: 'http://www.mokpo.ac.kr/' },
  { schoolName: '목포해양대학교', schoolType: '대학', establishType: '사립', region: '전남', website: 'http://www.mmu.ac.kr/g1/Default.aspx' },
  { schoolName: '순천대학교', schoolType: '대학', establishType: '사립', region: '전남', website: 'http://www.sunchon.ac.kr/' },
  { schoolName: '예수대학교', schoolType: '대학', establishType: '사립', region: '전북' },
  { schoolName: '우석대학교', schoolType: '대학', establishType: '사립', region: '전북', website: 'http://www.woosuk.ac.kr/WoosukEnglish.do' },
  { schoolName: '전북대학교', schoolType: '대학', establishType: '사립', region: '전북', website: 'http://www.jbnu.ac.kr/' },
  { schoolName: '전주교육대학교', schoolType: '교육대학', establishType: '국립', region: '전북', website: 'http://www.jnue.ac.kr/tindex.do' },
  { schoolName: '전주기전대학', schoolType: '대학', establishType: '사립', region: '전북', website: 'https://kijeon.ac.kr/' },
  { schoolName: '제주대학교', schoolType: '대학', establishType: '사립', region: '제주', website: 'http://www.jejunu.ac.kr/' },
  { schoolName: '제주한라대학교', schoolType: '대학', establishType: '사립', region: '제주', website: 'https://chu.ac.kr' },
  { schoolName: '나사렛대학교', schoolType: '대학', establishType: '사립', region: '충남', website: 'https://www.kornu.ac.kr' },
  { schoolName: '남서울대학교', schoolType: '대학', establishType: '사립', region: '충남', website: 'http://www.nsu.ac.kr/' },
  { schoolName: '백석대학교', schoolType: '대학', establishType: '사립', region: '충남', website: 'http://www.bu.ac.kr/' },
  { schoolName: '백석문화대학교', schoolType: '대학', establishType: '사립', region: '충남', website: 'https://www.bscu.ac.kr/' },
  { schoolName: '선문대학교', schoolType: '대학', establishType: '사립', region: '충남', website: 'http://tulip.sunmoon.ac.kr/english/main.do' },
  { schoolName: '유원대학교', schoolType: '대학', establishType: '사립', region: '충남', website: 'https://www.u1.ac.kr/' },
  { schoolName: '호서대학교', schoolType: '대학', establishType: '사립', region: '충남', website: 'http://www.hoseo.ac.kr/' },
]


/**
 * 시드 데이터에서 대학 검색
 */
export function searchSeedUniversities(query: string): PublicUniversityInfo[] {
  const q = query.toLowerCase()
  return KOREAN_UNIVERSITIES.filter(u =>
    u.schoolName.toLowerCase().includes(q) ||
    u.region.includes(query)
  )
}

/**
 * 시드 데이터에서 지역별 대학 조회
 */
export function getSeedUniversitiesByRegion(region: string): PublicUniversityInfo[] {
  return KOREAN_UNIVERSITIES.filter(u => u.region === region)
}

/**
 * 시드 데이터 전체 통계
 */
export function getSeedStats() {
  const regions = [...new Set(KOREAN_UNIVERSITIES.map(u => u.region).filter(Boolean))]
  const byRegion = regions.map(r => ({
    region: r,
    count: KOREAN_UNIVERSITIES.filter(u => u.region === r).length,
  })).sort((a, b) => b.count - a.count)

  return {
    total: KOREAN_UNIVERSITIES.length,
    byRegion,
    byType: {
      national: KOREAN_UNIVERSITIES.filter(u => u.establishType === '국립').length,
      private: KOREAN_UNIVERSITIES.filter(u => u.establishType === '사립').length,
      public: KOREAN_UNIVERSITIES.filter(u => u.establishType === '공립').length,
    },
  }
}
