/**
 * Help Content System
 *
 * LLM Hub의 종합 도움말 콘텐츠를 정의합니다.
 */

/**
 * 도움말 주제 카테고리
 */
export type HelpCategory =
  | 'getting-started'
  | 'providers'
  | 'features'
  | 'troubleshooting';

/**
 * 도움말 주제 인터페이스
 */
export interface HelpTopic {
  id: string;
  category: HelpCategory;
  title: string;
  summary: string;
  content: string | string[];
  relatedTopics?: string[];
  prerequisites?: string[];
}

/**
 * 모든 도움말 콘텐츠
 */
const helpContent: HelpTopic[] = [
  // ========== Getting Started ==========
  {
    id: 'what-is-llm-hub',
    category: 'getting-started',
    title: 'LLM Hub란?',
    summary: 'LLM Hub는 여러 AI 제공자를 통합 관리하는 시스템입니다.',
    content: [
      '# LLM Hub란?',
      '',
      'LLM Hub는 다양한 AI 언어 모델(LLM) 제공자를 하나의 시스템에서 통합 관리하는 플랫폼입니다.',
      '',
      '## 주요 기능',
      '',
      '- **다중 제공자 지원**: OpenAI, Anthropic, Google Gemini 등 11개 이상의 제공자 지원',
      '- **템플릿 기반 등록**: 복잡한 설정 없이 템플릿을 선택하여 빠르게 등록',
      '- **기능별 LLM 매핑**: 용도에 따라 자동으로 최적의 모델 선택',
      '- **폴 백(대체) 전략**: 주 제공자 실패 시 자동으로 대체 모델 사용',
      '- **비용 관리**: 사용량 추적 및 비용 모니터링',
      '',
      '## 왜 필요한가요?',
      '',
      '1. **유연성**: 특정 제공자에 종속되지 않고 다양한 모델 활용',
      '2. **비용 효율**: 용도에 따라 저렴한 모델과 고성능 모델을 적절히 선택',
      '3. **안정성**: 한 제공자에 문제가 생겨도 다른 제공자로 자동 전환',
      '4. **확장성**: 새로운 제공자가 나오면 쉽게 추가 가능',
    ],
    relatedTopics: ['quick-start', 'concepts'],
  },
  {
    id: 'quick-start',
    category: 'getting-started',
    title: '빠른 시작 가이드',
    summary: '첫 번째 LLM 제공자를 등록하는 방법을 안내합니다.',
    content: [
      '# 빠른 시작 가이드',
      '',
      '## 1단계: 제공자 선택',
      '',
      '1. 관리자 메뉴에서 **LLM 제공자**를 클릭합니다.',
      '2. **새 제공자 추가** 버튼을 클릭합니다.',
      '3. 제공자 템플릿 목록에서 원하는 제공자를 선택합니다.',
      '   - OpenAI: 가장 인기 있는 선택, GPT-4o 모델 제공',
      '   - Google Gemini: 비용 효율적, 한국어 성능 우수',
      '   - Ollama: 로컬에서 물뤂로 실행',
      '',
      '## 2단계: API 키 설정',
      '',
      '선택한 제공자의 API 키가 필요합니다.',
      '',
      '- **API 키 발급**: 각 제공자별 가이드를 참조하세요',
      '- **API 키 입력**: 발급받은 키를 안전하게 입력합니다',
      '- **기본 URL**: 템플릿에서 자동 설정 (직접 설정 모드에서만 수정)',
      '',
      '## 3단계: 연결 테스트',
      '',
      '1. **연결 테스트** 버튼을 클릭하여 API 연결을 확인합니다.',
      '2. 테스트가 성공하면 모델 목록이 자동으로 동기화됩니다.',
      '3. **저장** 버튼을 클릭하여 제공자를 등록합니다.',
      '',
      '## 4단계: 기능 매핑 설정 (선택사항)',
      '',
      '1. **LLM 기능 매핑** 메뉴로 이동합니다.',
      '2. 각 기능별로 사용할 모델을 설정합니다.',
      '3. 태그 기반 자동 매칭 또는 직접 모델 지정 중 선택합니다.',
      '',
      '## 다음 단계',
      '',
      '- **학생 분석**: AI 기반 학생 분석 기능 사용',
      '- **추가 제공자 등록**: 백업용 또는 특수 목적 제공자 추가',
      '- **비용 모니터링**: 사용량 및 비용 확인',
    ],
    relatedTopics: ['what-is-llm-hub', 'concepts', 'api-key-guide'],
  },
  {
    id: 'concepts',
    category: 'getting-started',
    title: '핵심 개념',
    summary: '제공자, 모델, 기능 매핑의 개념을 설명합니다.',
    content: [
      '# 핵심 개념',
      '',
      '## 제공자 (Provider)',
      '',
      'AI 모델을 제공하는 회사나 서비스입니다.',
      '',
      '예시:',
      '- OpenAI (GPT-4o, GPT-4o-mini)',
      '- Anthropic (Claude Sonnet, Claude Opus)',
      '- Google (Gemini 2.5 Flash, Gemini 2.0 Pro)',
      '- Ollama (로컬 실행)',
      '',
      '각 제공자는 고유한 API 키와 Base URL이 필요합니다.',
      '',
      '## 모델 (Model)',
      '',
      '제공자가 제공하는 특정 AI 모델입니다.',
      '',
      '모델별 특성:',
      '- **Context Window**: 한 번에 처리할 수 있는 텍스트 길이',
      '- **Vision 지원**: 이미지 분석 기능 제공 여부',
      '- **비용 티어**: 물뤂 / 저렴 / 중간 / 고가',
      '- **품질 티어**: 기본 / 균형 / 프리미엄',
      '',
      '## 기능 매핑 (Feature Mapping)',
      '',
      '특정 기능에 어떤 LLM을 사용할지 설정하는 것입니다.',
      '',
      '매칭 방식:',
      '- **태그 기반**: 조건에 맞는 모델 자동 선택',
      '- **직접 지정**: 특정 모델 강제 사용',
      '',
      '예시:',
      '- 학생 성향 분석 → 고품질 모델',
      '- 빠른 요약 → 저렴하고 빠른 모델',
      '- 이미지 분석 → Vision 지원 모델',
      '',
      '## 폴 백 (Fallback)',
      '',
      '주 모델을 사용할 수 없을 때 대체 모델을 사용하는 전략입니다.',
      '',
      '폴 백 모드:',
      '- **다음 우선순위**: 우선순위가 낮은 다음 규칙 사용',
      '- **사용 가능한 모델**: 조건을 만족하는 어떤 모델이든 사용',
      '- **실패**: 폴 백 없이 에러 반환',
    ],
    relatedTopics: ['what-is-llm-hub', 'feature-mapping'],
  },

  // ========== Providers ==========
  {
    id: 'provider-openai',
    category: 'providers',
    title: 'OpenAI 등록 방법',
    summary: 'OpenAI GPT 모델을 등록하는 방법입니다.',
    content: [
      '# OpenAI 등록 방법',
      '',
      '## OpenAI란?',
      '',
      'ChatGPT를 개발한 OpenAI의 API 서비스로, GPT-4o, GPT-4o-mini 등의 모델을 제공합니다.',
      '',
      '## 등록 단계',
      '',
      '### 1. API 키 발급',
      '',
      '1. [OpenAI Platform](https://platform.openai.com)에 로그인',
      '2. 왼쪽 메뉴에서 **API keys** 선택',
      '3. **Create new secret key** 버튼 클릭',
      '4. 키 이름 입력 (예: "AI Afterschool")',
      '5. **Create secret key** 클릭',
      '6. 생성된 키를 **즉시 복사** (한 번만 표시됨)',
      '',
      '### 2. LLM Hub에 등록',
      '',
      '1. 관리자 메뉴 → **LLM 제공자**',
      '2. **새 제공자 추가** 클릭',
      '3. **OpenAI GPT** 템플릿 선택',
      '4. **API 키** 필드에 복사한 키 붙여넣기',
      '5. **연결 테스트** 클릭',
      '6. 성공하면 **저장** 클릭',
      '',
      '## 제공 모델',
      '',
      '- **GPT-4o**: 최고 성능, Vision 지원, 비용 높음',
      '- **GPT-4o Mini**: GPT-4o의 경량 버전, Vision 지원, 비용 절감',
      '- **o3-mini**: 추론에 특화, 고급 문제 해결',
      '',
      '## 비용 안내',
      '',
      '사용량에 따라 비용이 청구됩니다. 자세한 요금은 [OpenAI Pricing](https://openai.com/pricing)에서 확인하세요.',
      '',
      '## 주의사항',
      '',
      '- API 키는 유출되지 않도록 안전하게 보관하세요',
      '- 묶음 결제를 설정하여 사용량을 모니터링하세요',
      '- Rate limit(분당 호출 제한)에 주의하세요',
    ],
    relatedTopics: ['provider-anthropic', 'api-key-guide', 'security'],
  },
  {
    id: 'provider-anthropic',
    category: 'providers',
    title: 'Anthropic Claude 등록 방법',
    summary: 'Anthropic Claude 모델을 등록하는 방법입니다.',
    content: [
      '# Anthropic Claude 등록 방법',
      '',
      '## Anthropic이란?',
      '',
      'Claude AI를 개발한 Anthropic의 API 서비스로, Claude Sonnet, Claude Opus 등의 모델을 제공합니다.',
      '',
      '## 등록 단계',
      '',
      '### 1. API 키 발급',
      '',
      '1. [Anthropic Console](https://console.anthropic.com)에 로그인',
      '2. 오른쪽 상단 **Settings** 클릭',
      '3. **API Keys** 탭 선택',
      '4. **Create Key** 버튼 클릭',
      '5. 키 이름 입력',
      '6. 생성된 키 복사',
      '',
      '### 2. LLM Hub에 등록',
      '',
      '1. 관리자 메뉴 → **LLM 제공자**',
      '2. **새 제공자 추가** 클릭',
      '3. **Anthropic Claude** 템플릿 선택',
      '4. **API 키** 필드에 키 입력',
      '5. **연결 테스트** 클릭',
      '6. 성공하면 **저장** 클릭',
      '',
      '## 제공 모델',
      '',
      '- **Claude Sonnet 4.5**: 균형잡힌 성능과 속도, Vision 지원',
      '- **Claude 3.5 Haiku**: 빠른 응답, 효율적인 비용',
      '- **Claude Opus 4**: 최고 품질, 복잡한 작업에 적합',
      '',
      '## 특징',
      '',
      '- **긴 Context Window**: 최대 200K 토큰 지원',
      '- **강력한 Vision**: 이미지 분석 능력 우수',
      '- **안전성**: 유해 콘텐츠 생성을 억제',
      '',
      '## 비용 안내',
      '',
      'OpenAI와 유사한 가격대이며, 사용량 기반 과금입니다.',
    ],
    relatedTopics: ['provider-openai', 'provider-google', 'api-key-guide'],
  },
  {
    id: 'provider-google',
    category: 'providers',
    title: 'Google Gemini 등록 방법',
    summary: 'Google Gemini 모델을 등록하는 방법입니다.',
    content: [
      '# Google Gemini 등록 방법',
      '',
      '## Google Gemini란?',
      '',
      'Google의 AI 모델 시리즈로, Gemini 2.5 Flash, Gemini 2.0 Pro 등을 제공합니다. 한국어 성능이 우수하고 비용 효율적입니다.',
      '',
      '## 등록 단계',
      '',
      '### 1. API 키 발급',
      '',
      '1. [Google AI Studio](https://aistudio.google.com)에 로그인',
      '2. 왼쪽 메뉴에서 **Get API key** 선택',
      '3. **Create API Key** 버튼 클릭',
      '4. Google Cloud 프로젝트 선택 (또는 생성)',
      '5. 생성된 키 복사',
      '',
      '### 2. LLM Hub에 등록',
      '',
      '1. 관리자 메뉴 → **LLM 제공자**',
      '2. **새 제공자 추가** 클릭',
      '3. **Google Gemini** 템플릿 선택',
      '4. **API 키** 필드에 키 입력',
      '5. **연결 테스트** 클릭',
      '6. 성공하면 **저장** 클릭',
      '',
      '## 제공 모델',
      '',
      '- **Gemini 2.5 Flash**: 초고속, 대용량 컨텍스트(1M 토큰), Vision 지원',
      '- **Gemini 2.0 Flash**: 균형잡힌 성능, Vision 지원',
      '- **Gemini 2.0 Flash Lite**: 가벼운 버전, 비용 효율적',
      '',
      '## 장점',
      '',
      '- **한국어**: 한국어 처리 능력 우수',
      '- **Context Window**: 100만 토큰으로 매우 긴 텍스트 처리 가능',
      '- **비용**: OpenAI, Anthropic 대비 저렴',
      '- **Vision**: 이미지 분석 우수',
      '',
      '## 물뤂 사용',
      '',
      'Google AI Studio에서 제공하는 물뤂 사용량이 있으며, 이후 유료로 전환됩니다.',
    ],
    relatedTopics: ['provider-openai', 'provider-anthropic', 'cost-optimization'],
  },
  {
    id: 'provider-ollama',
    category: 'providers',
    title: 'Ollama(로컬 LLM) 등록 방법',
    summary: '로컬 환경에서 물뤂로 실행하는 Ollama를 등록하는 방법입니다.',
    content: [
      '# Ollama(로컬 LLM) 등록 방법',
      '',
      '## Ollama란?',
      '',
      '로컬 컴퓨터에서 오픈소스 LLM을 물뤂로 실행할 수 있게 해주는 도구입니다. Llama, Mistral, Phi 등의 모델을 지원합니다.',
      '',
      '## 설치 방법',
      '',
      '### macOS/Linux',
      '',
      '```bash',
      'curl -fsSL https://ollama.com/install.sh | sh',
      '```',
      '',
      '### Windows',
      '',
      '[Ollama 다운로드 페이지](https://ollama.com/download)에서 설치 프로그램 다운로드',
      '',
      '## Ollama 서버 실행',
      '',
      '```bash',
      'ollama serve',
      '```',
      '',
      '기본적으로 http://localhost:11434 에서 실행됩니다.',
      '',
      '## 모델 다운로드',
      '',
      '```bash',
      '# Llama 3.2 (3B) - 가벼운 모델',
      'ollama pull llama3.2:3b',
      '',
      '# Mistral (7B) - 균형잡힌 성능',
      'ollama pull mistral:7b',
      '',
      '# Phi-4 - Microsoft의 모델',
      'ollama pull phi4',
      '```',
      '',
      '## LLM Hub에 등록',
      '',
      '1. 관리자 메뉴 → **LLM 제공자**',
      '2. **새 제공자 추가** 클릭',
      '3. **Ollama** 템플릿 선택',
      '4. **Base URL** 확인 (기본값: http://localhost:11434/api)',
      '5. **API 키** 필드는 비워두세요 (로컬 실행 시 불필요)',
      '6. **연결 테스트** 클릭',
      '7. 성공하면 **저장** 클릭',
      '',
      '## 장점',
      '',
      '- **데이터 프라이버시**: 모든 데이터가 로컬에만 저장',
      '- **비용**: 완전 물뤂',
      '- **오프라인**: 인터넷 없이도 사용 가능',
      '',
      '## 단점',
      '',
      '- **성능**: 클라우드 모델보다 성능이 낮을 수 있음',
      '- **하드웨어**: 충분한 RAM과 GPU 필요',
      '- **설정**: 초기 설정이 필요',
      '',
      '## 추천 사용 사례',
      '',
      '- 민감한 데이터 처리',
      '- 개발/테스트 환경',
      '- 인터넷 연결이 불안정한 환경',
    ],
    relatedTopics: ['provider-custom', 'concepts'],
  },
  {
    id: 'provider-custom',
    category: 'providers',
    title: '직접 설정으로 등록하기',
    summary: 'OpenAI 호환 API를 사용하는 커스텀 제공자를 등록하는 방법입니다.',
    content: [
      '# 직접 설정으로 등록하기',
      '',
      '## 언제 사용하나요?',
      '',
      '템플릿에 없는 제공자를 추가하거나, OpenAI API 호환 형식을 사용하는 서비스를 등록할 때 사용합니다.',
      '',
      '지원 예시:',
      '- Azure OpenAI',
      '- Together AI',
      '- Fireworks AI',
      '- LocalAI',
      '- vLLM (자체 호스팅)',
      '',
      '## 등록 단계',
      '',
      '### 1. 제공자 정보 입력',
      '',
      '1. 관리자 메뉴 → **LLM 제공자**',
      '2. **새 제공자 추가** 클릭',
      '3. **직접 설정** 모드 선택 (또는 "직접 설정 (OpenAI 호환)" 템플릿)',
      '4. 다음 정보 입력:',
      '',
      '| 필드 | 설명 | 예시 |',
      '|------|------|------|',
      '| **이름** | 제공자 표시 이름 | "My Azure OpenAI" |',
      '| **제공자 유형** | 기본 형식 | openai (OpenAI 호환) |',
      '| **Base URL** | API 엔드포인트 | https://my-resource.openai.azure.com |',
      '| **API 키** | 인증 키 | your-api-key-here |',
      '| **인증 유형** | 인증 방식 | api_key |',
      '',
      '### 2. 모델 설정',
      '',
      '**모델 동기화** 버튼을 클릭하거나, 수동으로 모델을 추가합니다.',
      '',
      '수동 추가 시 필요한 정보:',
      '- 모델 ID (API에서 사용하는 ID)',
      '- 표시 이름',
      '- Context Window 크기',
      '- Vision 지원 여부',
      '',
      '### 3. 기능 설정',
      '',
      '제공자가 지원하는 기능을 선택합니다:',
      '- Streaming (실시간 응답)',
      '- Vision (이미지 분석)',
      '- Function Calling (도구 사용)',
      '- JSON Mode (구조화된 출력)',
      '',
      '## Azure OpenAI 예시',
      '',
      '- **Base URL**: `https://{resource-name}.openai.azure.com/openai/deployments/{deployment-name}`',
      '- **API 키**: Azure Portal에서 발급',
      '- **커스텀 헤더**: `api-key` (Azure는 Authorization 대신 api-key 헤더 사용)',
      '',
      '## 문제 해결',
      '',
      '연결 테스트가 실패하면:',
      '1. Base URL이 정확한지 확인',
      '2. API 키 권한 확인',
      '3. 인증 헤더 이름 확인 (Authorization vs api-key)',
      '4. 네트워크 연결 확인',
    ],
    relatedTopics: ['provider-openai', 'connection-failed'],
  },
  {
    id: 'api-key-guide',
    category: 'providers',
    title: 'API 키는 어디서 얻나요?',
    summary: '각 제공자별 API 키 발급 방법을 안내합니다.',
    content: [
      '# API 키는 어디서 얻나요?',
      '',
      '## 제공자별 발급 방법',
      '',
      '### OpenAI',
      '',
      '1. [platform.openai.com/api-keys](https://platform.openai.com/api-keys)',
      '2. Create new secret key',
      '3. 키 이름 입력 → Create',
      '4. 생성된 키 즉시 복사 (한 번만 표시)',
      '',
      '### Anthropic (Claude)',
      '',
      '1. [console.anthropic.com/settings/keys](https://console.anthropic.com/settings/keys)',
      '2. Create Key',
      '3. 키 이름 입력',
      '4. 생성된 키 복사',
      '',
      '### Google (Gemini)',
      '',
      '1. [aistudio.google.com/app/apikey](https://aistudio.google.com/app/apikey)',
      '2. Create API Key in new project',
      '3. Google Cloud 프로젝트 선택',
      '4. 생성된 키 복사',
      '',
      '### Ollama',
      '',
      '로컬 실행 시 API 키가 필요 없습니다.',
      '',
      '### DeepSeek',
      '',
      '1. [platform.deepseek.com/api_keys](https://platform.deepseek.com/api_keys)',
      '2. Create API Key',
      '',
      '### Mistral AI',
      '',
      '1. [console.mistral.ai/api-keys](https://console.mistral.ai/api-keys/)',
      '2. Create API Key',
      '',
      '### 기타 제공자',
      '',
      '| 제공자 | API 키 발급 URL |',
      '|--------|-----------------|',
      '| Cohere | dashboard.cohere.com/api-keys |',
      '| xAI (Grok) | console.x.ai |',
      '| Zhipu AI | open.bigmodel.cn/usercenter/apikeys |',
      '| Moonshot | platform.moonshot.cn/console/api-keys |',
      '',
      '## API 키 보안 팁',
      '',
      '1. **키 공유 금지**: API 키는 비밀번호와 같이 취급하세요',
      '2. **별도 키 사용**: 각 시스템마다 별도의 키를 발급받아 사용',
      '3. **정기 교체**: 주기적으로 키를 재발급받아 사용',
      '4. **사용량 모니터링**: 이상 징후 발견 시 즉시 키 재발급',
    ],
    relatedTopics: ['security', 'provider-openai', 'provider-anthropic', 'provider-google'],
  },
  {
    id: 'security',
    category: 'providers',
    title: 'API 키 보안',
    summary: 'API 키의 안전한 저장과 관리 방법을 설명합니다.',
    content: [
      '# API 키 보안',
      '',
      '## 저장 방식',
      '',
      'LLM Hub에서는 API 키를 다음과 같이 안전하게 저장합니다:',
      '',
      '### 암호화 저장',
      '',
      '- 데이터베이스에 AES-256-GCM 알고리즘으로 암호화하여 저장',
      '- 암호화 키는 환경 변수로 관리',
      '- 평문 키는 메모리에만 일시적으로 보관',
      '',
      '### 전송 보안',
      '',
      '- HTTPS/TLS 1.3으로 모든 통신 암호화',
      '- API 키는 HTTP 헤더에 포함되어 전송',
      '- 로그에 키가 남지 않도록 마스킹 처리',
      '',
      '## 보안 권장사항',
      '',
      '### 1. 최소 권한 원칙',
      '',
      '- API 키에 필요한 최소한의 권한만 부여',
      '- 읽기 전용 키와 쓰기 키를 분리하여 사용',
      '',
      '### 2. 키 순환 (Rotation)',
      '',
      '- 정기적으로 (예: 90일마다) API 키 재발급',
      '- 의심스러운 활동 발견 시 즉시 재발급',
      '',
      '### 3. 사용량 모니터링',
      '',
      '- 각 제공자의 대시보드에서 사용량 정기 확인',
      '- 이상 징후 (예상보다 높은 사용량) 발견 시 조치',
      '',
      '### 4. 환경 분리',
      '',
      '- 개발/테스트/운영 환경마다 별도의 키 사용',
      '- 개발용 키는 사용량 제한 설정',
      '',
      '## 키 유출 시 대응',
      '',
      '1. **즉시 재발급**: 해당 키 폐기 및 새 키 발급',
      '2. **사용량 확인**: 유출 기간 동안의 사용량 확인',
      '3. **알림 설정**: 제공자별 이상 사용량 알림 설정',
      '',
      '## 로그 및 감사',
      '',
      'LLM Hub에서는 다음을 기록합니다:',
      '- API 호출 로그 (키는 마스킹)',
      '- 제공자 추가/수정/삭제 이력',
      '- 에러 로그',
    ],
    relatedTopics: ['api-key-guide', 'rate-limit'],
  },

  // ========== Features ==========
  {
    id: 'feature-mapping',
    category: 'features',
    title: '기능별 LLM 매핑이란?',
    summary: '각 기능에 어떤 LLM을 사용할지 설정하는 기능을 설명합니다.',
    content: [
      '# 기능별 LLM 매핑이란?',
      '',
      '## 개념',
      '',
      '각 기능(학생 분석, 상담 보고서 등)마다 어떤 LLM을 사용할지 설정하는 시스템입니다.',
      '',
      '## 매핑 방식',
      '',
      '### 1. 태그 기반 자동 매칭',
      '',
      '조건에 맞는 모델을 자동으로 선택합니다.',
      '',
      '예시:',
      '- **필수 태그**: ["premium", "korean"]',
      '- **제외 태그**: ["vision"]', 
      '- **비용 티어**: medium 이하',
      '- **품질 티어**: premium',
      '',
      '→ 위 조건을 만족하는 모델 중에서 자동 선택',
      '',
      '### 2. 직접 모델 지정',
      '',
      '특정 모델을 강제로 사용합니다.',
      '',
      '예시:',
      '- 제공자: OpenAI',
      '- 모델: gpt-4o',
      '',
      '→ 항상 이 모델을 사용',
      '',
      '## 우선순위',
      '',
      '매핑 규칙은 우선순위가 높은 순서대로 적용됩니다.',
      '',
      '예시:',
      '1. **우선순위 1**: 특정 모델 직접 지정 (VIP 기능용)',
      '2. **우선순위 2**: premium 태그 모델 (일반 분석용)',
      '3. **우선순위 3**: 어떤 모델이든 사용 가능 (백업용)',
      '',
      '## 폴 백 전략',
      '',
      '주 규칙을 사용할 수 없을 때의 대처 방식:',
      '',
      '- **다음 우선순위**: 우선순위가 낮은 다음 규칙으로 폴 백',
      '- **사용 가능한 모델**: 조건을 만족하는 어떤 모델이든 사용',
      '- **실패**: 폴 백 없이 에러 발생',
    ],
    relatedTopics: ['auto-tag-match', 'specific-model', 'fallback', 'concepts'],
  },
  {
    id: 'auto-tag-match',
    category: 'features',
    title: '태그 기반 자동 매칭 사용법',
    summary: '태그를 사용하여 조건에 맞는 모델을 자동 선택하는 방법입니다.',
    content: [
      '# 태그 기반 자동 매칭 사용법',
      '',
      '## 태그 종류',
      '',
      '### 기능 태그',
      '',
      '| 태그 | 설명 |',
      '|------|------|',
      '| `vision` | 이미지 분석 기능 지원 |',
      '| `streaming` | 실시간 응답 스트리밍 지원 |',
      '| `function_calling` | 도구/함수 호출 지원 |',
      '| `json_mode` | 구조화된 JSON 출력 지원 |',
      '| `tools` | 도구 사용 지원 |',
      '',
      '### 비용 태그',
      '',
      '| 태그 | 설명 |',
      '|------|------|',
      '| `free` | 물뤂 사용 가능 |',
      '| `low` | 저렴한 비용 |',
      '| `medium` | 중간 비용 |',
      '| `high` | 높은 비용 |',
      '',
      '### 품질 태그',
      '',
      '| 태그 | 설명 |',
      '|------|------|',
      '| `basic` | 기본 품질 |',
      '| `balanced` | 균형잡힌 품질/비용 |',
      '| `premium` | 프리미엄 품질 |',
      '',
      '### 언어 태그',
      '',
      '| 태그 | 설명 |',
      '|------|------|',
      '| `korean` | 한국어에 최적화 |',
      '| `multilingual` | 다국어 지원 |',
      '',
      '## 사용 예시',
      '',
      '### 예시 1: 학생 분석',
      '',
      '**요구사항**: 한국어 지원, 고품질, 비용 고려',
      '',
      '설정:',
      '- 필수 태그: ["korean", "premium"]',
      '- 제외 태그: []',
      '- 최대 비용 티어: medium',
      '',
      '→ 한국어 지원하는 프리미엄 모델 중 비용이 medium 이하인 모델 선택',
      '',
      '### 예시 2: 이미지 분석',
      '',
      '**요구사항**: Vision 기능 필수',
      '',
      '설정:',
      '- 필수 태그: ["vision"]',
      '- 제외 태그: []',
      '',
      '→ Vision 지원하는 모델 중에서 선택',
      '',
      '### 예시 3: 빠른 응답',
      '',
      '**요구사항**: 속도 우선, 비용 절감',
      '',
      '설정:',
      '- 필수 태그: ["low", "balanced"]',
      '- 제외 태그: ["high"]',
      '',
      '→ 저렴하고 균형잡힌 모델 선택',
    ],
    relatedTopics: ['feature-mapping', 'specific-model', 'fallback'],
  },
  {
    id: 'specific-model',
    category: 'features',
    title: '직접 모델 지정 사용법',
    summary: '특정 모델을 강제로 사용하는 방법입니다.',
    content: [
      '# 직접 모델 지정 사용법',
      '',
      '## 언제 사용하나요?',
      '',
      '- **예측 가능성**: 항상 같은 모델을 사용해야 할 때',
      '- **품질 보장**: 특정 모델의 성능이 검증되었을 때',
      '- **규정 준수**: 특정 모델만 사용해야 하는 경우',
      '- **테스트**: 특정 모델 동작을 테스트할 때',
      '',
      '## 설정 방법',
      '',
      '### 1단계: 매칭 모드 선택',
      '',
      '기능 매핑 설정에서 **직접 지정**을 선택합니다.',
      '',
      '### 2단계: 제공자 선택',
      '',
      '드롭다운에서 사용할 제공자를 선택합니다.',
      '',
      '### 3단계: 모델 선택',
      '',
      '선택한 제공자의 모델 목록에서 원하는 모델을 선택합니다.',
      '',
      '## 사용 예시',
      '',
      '### VIP 분석 기능',
      '',
      '**설정**:',
      '- 제공자: OpenAI',
      '- 모델: gpt-4o',
      '',
      '→ VIP 고객의 분석에는 항상 GPT-4o 사용',
      '',
      '### 이미지 분석',
      '',
      '**설정**:',
      '- 제공자: Google',
      '- 모델: gemini-2.5-flash-preview-05-20',
      '',
      '→ 이미지 분석에는 항상 Gemini Flash 사용',
      '',
      '### 비용 절감용',
      '',
      '**설정**:',
      '- 제공자: OpenAI',
      '- 모델: gpt-4o-mini',
      '',
      '→ 일반 작업에는 비용 효율적인 Mini 사용',
      '',
      '## 주의사항',
      '',
      '- 직접 지정한 모델이 비활성화되면 에러가 발생할 수 있습니다',
      '- 폴 백 설정을 함께 사용하는 것을 권장합니다',
      '',
    ],
    relatedTopics: ['feature-mapping', 'auto-tag-match', 'fallback'],
  },
  {
    id: 'fallback',
    category: 'features',
    title: '폴 백(대체) 전략 설정',
    summary: '주 모델을 사용할 수 없을 때의 대체 전략을 설정합니다.',
    content: [
      '# 폴 백(대체) 전략 설정',
      '',
      '## 폴 백이란?',
      '',
      '주로 사용하려는 모델을 사용할 수 없을 때 (API 오류, Rate limit 등) 대체 모델을 사용하는 기능입니다.',
      '',
      '## 폴 백 모드',
      '',
      '### 1. 다음 우선순위 (next_priority)',
      '',
      '현재 규칙을 사용할 수 없으면 우선순위가 낮은 다음 규칙으로 폴 백합니다.',
      '',
      '예시:',
      '1. **우선순위 1**: GPT-4o 직접 지정 ❌ 실패',
      '2. **우선순위 2**: premium 태그 모델 ✅ 사용',
      '',
      '### 2. 사용 가능한 모델 (any_available)',
      '',
      '현재 규칙의 조건을 만족하는 다른 모델을 찾아 사용합니다.',
      '',
      '예시:',
      '- 규칙: ["premium", "korean"] 태그 모델',
      '- Claude 실패 → Gemini로 폴 백 (같은 조건 만족)',
      '',
      '### 3. 실패 (fail)',
      '',
      '폴 백 없이 에러를 반환합니다.',
      '',
      '사용 사례:',
      '- 특정 모델의 성능이 필수적인 경우',
      '- 폴 백을 허용하지 않는 비즈니스 규칙이 있는 경우',
      '',
      '## 폴 백 체인 미리보기',
      '',
      '설정 화면에서 폴 백 체인을 미리 볼 수 있습니다.',
      '',
      '예시:',
      '```',
      '학생 성향 분석',
      '├─ 1순위: GPT-4o (직접 지정)',
      '├─ 2순위: Claude Sonnet (premium 태그)',
      '└─ 3순위: Gemini Flash (balanced 태그)',
      '```',
      '',
      '## 권장 설정',
      '',
      '| 기능 | 주 모델 | 폴 백 모드 | 이유 |',
      '|------|---------|-----------|------|',
      '| 중요 분석 | GPT-4o | 다음 우선순위 | 품질 유지 |',
      '| 일반 작업 | Gemini | 사용 가능한 모델 | 가용성 우선 |',
      '| 테스트 | 특정 모델 | 실패 | 예측 가능성 |',
    ],
    relatedTopics: ['feature-mapping', 'auto-tag-match', 'specific-model'],
  },
  {
    id: 'vision-features',
    category: 'features',
    title: '이미지 분석 기능 설정',
    summary: 'Vision(이미지 분석) 기능을 사용하는 방법을 설명합니다.',
    content: [
      '# 이미지 분석 기능 설정',
      '',
      '## Vision이란?',
      '',
      'LLM이 이미지를 이해하고 분석하는 기능입니다. 관상 분석, 손금 분석 등에 사용됩니다.',
      '',
      '## Vision 지원 모델',
      '',
      '| 제공자 | 모델 |',
      '|--------|------|',
      '| OpenAI | GPT-4o, GPT-4o-mini |',
      '| Anthropic | Claude Sonnet, Claude Opus |',
      '| Google | Gemini 2.5 Flash, Gemini 2.0 Flash |',
      '| xAI | Grok 3 |',
      '| Zhipu | GLM-4V Plus |',
      '',
      '## 기능 매핑 설정',
      '',
      '### 태그 기반 설정',
      '',
      '```',
      '필수 태그: ["vision"]',
      '```',
      '',
      '→ Vision 지원 모델 중에서 자동 선택',
      '',
      '### 직접 지정',
      '',
      '```',
      '제공자: OpenAI',
      '모델: gpt-4o',
      '```',
      '',
      '→ 항상 GPT-4o 사용 (Vision 지원)',
      '',
      '## 사용 예시',
      '',
      '### 관상 분석',
      '',
      '**설정**:',
      '- 기능: 관상 분석',
      '- 매칭 모드: 태그 기반',
      '- 필수 태그: ["vision", "korean"]',
      '',
      '→ 한국어 잘하는 Vision 모델 선택',
      '',
      '### 손금 분석',
      '',
      '**설정**:',
      '- 기능: 손금 분석',
      '- 매칭 모드: 직접 지정',
      '- 모델: Gemini 2.5 Flash',
      '',
      '→ Gemini로 손금 분석',
      '',
      '## 주의사항',
      '',
      '- Vision 모델은 일반 모델보다 비용이 높을 수 있습니다',
      '- 이미지 크기에 따라 비용이 달라질 수 있습니다',
      '- Vision 기능이 필요 없는 작업에는 일반 모델을 사용하세요',
    ],
    relatedTopics: ['feature-mapping', 'auto-tag-match', 'cost-optimization'],
  },

  {
    id: 'smart-matching',
    category: 'features',
    title: '스마트 배정 (궁합 분석)',
    summary: '학생-선생님 궁합을 분석하여 최적의 배정을 추천하는 기능입니다.',
    content: [
      '# 스마트 배정 (궁합 분석)',
      '',
      '## 개요',
      '',
      '미배정 학생을 선택하면 모든 선생님과의 궁합 점수를 분석하여 최적의 매칭을 추천합니다.',
      '',
      '## 계산 모델',
      '',
      '### 1. 기본 점수 모델 (Rule-based)',
      '',
      '수학적 공식으로 궁합 점수를 계산합니다. 빠르고 일관성 있는 결과를 제공합니다.',
      '',
      '**점수 배분 (총 100점):**',
      '',
      '| 항목 | 배점 | 설명 |',
      '|------|------|------|',
      '| MBTI 유사도 | 25점 | 성격 유형 호환성 |',
      '| 학습 스타일 | 25점 | 교육 방식 호환성 |',
      '| 사주 오행 | 20점 | 오행 상생/상극 관계 |',
      '| 성명학 | 15점 | 4격 수리 조화 |',
      '| 부하 분산 | 15점 | 담당 학생 수 균형 |',
      '',
      '### 2. LLM 기반 분석 (AI 추천)',
      '',
      'AI가 학생과 선생님의 데이터를 종합적으로 분석하여 점수와 추천 이유를 제공합니다.',
      '',
      '**점수 배분 (총 100점):**',
      '',
      '| 항목 | 배점 | 설명 |',
      '|------|------|------|',
      '| MBTI | 20점 | 소통 호환성 |',
      '| 학습 스타일 | 10점 | 교육 방식 적합도 |',
      '| **사주** | **50점** | 오행 상생/상극, 천간·지지 궁합, 일간 호환성 |',
      '| 성명학 | 10점 | 4격 조화 |',
      '| 부하 분산 | 10점 | 담당 학생 수 |',
      '',
      '**특징:**',
      '- 사주 분석에 가장 큰 비중 (50%)을 두어 깊이 있는 궁합 판단',
      '- AI가 한국어로 구체적인 추천 이유를 제공',
      '- 분석에 20~30초 소요',
      '- LLM 제공자 설정이 필요 (관리자 > LLM 제공자)',
      '',
      '## 사용 방법',
      '',
      '1. **배정 > 스마트 배정** 메뉴로 이동',
      '2. **미배정 학생** 드롭다운에서 학생 선택',
      '3. **계산 모델** 드롭다운에서 원하는 모델 선택',
      '4. 분석 결과에서 추천 선생님 목록 확인',
      '5. **배정하기** 버튼으로 학생을 선생님에게 배정',
      '',
      '## 모델 변경 시',
      '',
      '학생이 이미 선택된 상태에서 계산 모델을 변경하면 자동으로 재분석됩니다.',
      '',
      '## LLM 기반 분석 사용 시 주의사항',
      '',
      '- **LLM 제공자 필수**: 관리자 > LLM 제공자에서 최소 1개 제공자가 활성화되어야 합니다',
      '- **비용 발생**: AI 호출 시 토큰 사용량에 따라 비용이 발생합니다',
      '- **응답 시간**: 선생님 수에 따라 20~60초 소요될 수 있습니다',
    ],
    relatedTopics: ['feature-mapping', 'cost-optimization', 'no-model-found'],
  },

  // ========== Troubleshooting ==========
  {
    id: 'connection-failed',
    category: 'troubleshooting',
    title: '연결 테스트 실패 시',
    summary: '제공자 연결 테스트가 실패할 때의 해결 방법입니다.',
    content: [
      '# 연결 테스트 실패 시',
      '',
      '## 일반적인 원인',
      '',
      '### 1. 잘못된 API 키',
      '',
      '**증상**: 401 Unauthorized, "Invalid API key"',
      '',
      '**해결**:',
      '- API 키를 다시 확인 (복사 시 공백 주의)',
      '- 새로운 API 키 발급',
      '- API 키에 필요한 권한이 있는지 확인',
      '',
      '### 2. 잘못된 Base URL',
      '',
      '**증상**: 404 Not Found, Connection refused',
      '',
      '**해결**:',
      '- URL에 오타가 없는지 확인',
      '- 프로토콜 (https://) 확인',
      '- 맨 끝의 슬래시 (/) 확인',
      '',
      '### 3. 네트워크 문제',
      '',
      '**증상**: Timeout, Connection timeout',
      '',
      '**해결**:',
      '- 인터넷 연결 확인',
      '- 방화벽 설정 확인',
      '- VPN/프록시 설정 확인',
      '',
      '### 4. Rate Limit',
      '',
      '**증상**: 429 Too Many Requests',
      '',
      '**해결**:',
      '- 잠시 후 다시 시도',
      '- Rate limit 정책 확인',
      '',
      '## 제공자별 특이사항',
      '',
      '### Azure OpenAI',
      '',
      '- **인증 헤더**: `api-key` 헤더 사용 (Authorization 아님)',
      '- **Base URL**: 배포 이름 포함 필요',
      '',
      '### Ollama',
      '',
      '- **로컬 실행**: Ollama 서버가 실행 중인지 확인',
      '- **포트**: 기본 11434번 포트',
      '',
      '### Google Gemini',
      '',
      '- **프로젝트**: Google Cloud 프로젝트 설정 필요',
      '- **결제**: 물뤂 사용량 초과 시 결제 설정 필요',
      '',
      '## 디버깅 방법',
      '',
      '1. **브라우저 개발자 도구** (F12) → Network 탭',
      '2. 연결 테스트 요청 확인',
      '3. 응답 코드와 메시지 확인',
    ],
    relatedTopics: ['rate-limit', 'no-model-found', 'api-key-guide'],
  },
  {
    id: 'rate-limit',
    category: 'troubleshooting',
    title: 'API 호출 한도 초과',
    summary: 'Rate limit 에러 발생 시 대처 방법입니다.',
    content: [
      '# API 호출 한도 초과',
      '',
      '## Rate Limit이란?',
      '',
      '제공자가 설정한 분당/시간당 API 호출 제한입니다. 초과하면 일시적으로 요청이 차단됩니다.',
      '',
      '## 제공자별 한도',
      '',
      '| 제공자 | 물뤂 등급 | 유료 등급 |',
      '|--------|-----------|-----------|',
      '| OpenAI | 3 RPM | 60-10,000 RPM |',
      '| Anthropic | - | 40-4,000 RPM |',
      '| Google | 60 RPM | 60-10,000 RPM |',
      '',
      '*RPM = Requests Per Minute (분당 요청 수)',
      '',
      '## 해결 방법',
      '',
      '### 1. 잠시 대기',
      '',
      'Rate limit은 보통 1분 내에 리셋됩니다. 잠시 후 다시 시도하세요.',
      '',
      '### 2. 여러 제공자 사용',
      '',
      'LLM Hub의 **폴 백** 기능으로 여러 제공자를 등록하세요.',
      '',
      '한 제공자가 Rate limit에 걸리면 다른 제공자로 자동 전환됩니다.',
      '',
      '### 3. 사용량 줄이기',
      '',
      '- 불필요한 API 호출 제거',
      '- 캐싱 활용',
      '- 배치 처리 사용',
      '',
      '### 4. 유료 등급 업그레이드',
      '',
      '제공자별로 더 높은 한도를 제공하는 유료 등급이 있습니다.',
      '',
      '## 예방책',
      '',
      '### 모니터링',
      '',
      '각 제공자의 대시보드에서 사용량을 모니터링하세요.',
      '',
      '### 알림 설정',
      '',
      '사용량이 임계값에 도달하면 알림을 받도록 설정하세요.',
      '',
      '### 폴 백 체인',
      '',
      '여러 제공자를 등록하고 폴 백 체인을 설정하여 가용성을 확보하세요.',
    ],
    relatedTopics: ['fallback', 'connection-failed', 'cost-optimization'],
  },
  {
    id: 'no-model-found',
    category: 'troubleshooting',
    title: '적절한 모델을 찾을 수 없을 때',
    summary: '기능 매핑에서 모델을 찾을 수 없을 때의 해결 방법입니다.',
    content: [
      '# 적절한 모델을 찾을 수 없을 때',
      '',
      '## 증상',
      '',
      '기능을 사용하려 할 때 "조건을 만족하는 모델을 찾을 수 없습니다" 에러 발생',
      '',
      '## 원인과 해결',
      '',
      '### 1. 태그 조건이 너무 엄격함',
      '',
      '**예시**:',
      '- 필수 태그: ["vision", "premium", "korean", "free"]',
      '- 문제: Vision + Premium + 한국어 + 물뤂 = 존재하지 않음',
      '',
      '**해결**:',
      '- 조건을 완화 (예: "free" 태그 제거)',
      '- 또는 폴 백 모드를 "any_available"로 변경',
      '',
      '### 2. 제공자가 비활성화됨',
      '',
      '**해결**:',
      '- 관리자 → LLM 제공자에서 제공자 상태 확인',
      '- 비활성화된 제공자 활성화',
      '',
      '### 3. 모델이 동기화되지 않음',
      '',
      '**해결**:',
      '- 제공자 상세 페이지에서 **모델 동기화** 클릭',
      '',
      '### 4. Vision 기능이 필요한데 Vision 모델이 없음',
      '',
      '**해결**:',
      '- Vision 지원 제공자 추가 (OpenAI, Google, Anthropic 등)',
      '- 필수 태그에서 "vision" 제거 (Vision 기능 포기)',
      '',
      '## 디버깅',
      '',
      '### 기능 매핑 미리보기',
      '',
      '관리자 → LLM 기능 매핑 → 미리보기 기능으로 어떤 모델이 선택되는지 확인하세요.',
      '',
      '### 폴 백 체인 확인',
      '',
      '폴 백 체인이 설정되어 있는지 확인하세요.',
    ],
    relatedTopics: ['feature-mapping', 'auto-tag-match', 'fallback', 'vision-features'],
  },
  {
    id: 'cost-optimization',
    category: 'troubleshooting',
    title: '비용 절약 팁',
    summary: 'LLM 사용 비용을 절감하는 방법을 안내합니다.',
    content: [
      '# 비용 절약 팁',
      '',
      '## 1. 적절한 모델 선택',
      '',
      '### 작업별 권장 모델',
      '',
      '| 작업 유형 | 권장 모델 | 비용 대비 |',
      '|-----------|-----------|-----------|',
      '| 간단한 요약 | GPT-4o-mini | ⭐⭐⭐ |',
      '| 일반 분석 | Gemini Flash | ⭐⭐⭐ |',
      '| 복잡한 추론 | GPT-4o, Claude | ⭐⭐ |',
      '| 이미지 분석 | Gemini Flash | ⭐⭐⭐ |',
      '',
      '### 기능 매핑 활용',
      '',
      '중요도에 따라 다른 모델을 사용하도록 설정하세요:',
      '',
      '```',
      '일반 작업 → 저렴한 모델',
      '중요 작업 → 고품질 모델',
      '```',
      '',
      '## 2. 폴 백 전략',
      '',
      '여러 제공자를 등록하고 비용 티어를 고려하여 폴 백 체인을 설정하세요.',
      '',
      '예시:',
      '1. **1순위**: Google Gemini (저렴)',
      '2. **2순위**: OpenAI GPT-4o-mini (중간)',
      '3. **3순위**: OpenAI GPT-4o (비쌈)',
      '',
      '## 3. 사용량 모니터링',
      '',
      '각 제공자의 대시보드에서 사용량을 주기적으로 확인하세요.',
      '',
      '이상 징후:',
      '- 예상보다 높은 사용량',
      '- 특정 시간대에 급증',
      '',
      '## 4. 로컬 모델 활용',
      '',
      'Ollama 등 로컬 모델을 사용하여 완전 물뤂으로 처리할 수 있습니다.',
      '',
      '적합한 작업:',
      '- 개발/테스트',
      '- 민감한 데이터 처리',
      '- 간단한 텍스트 처리',
      '',
      '## 5. 제공자별 물뤂 사용량 활용',
      '',
      '| 제공자 | 물뤂 제공량 |',
      '|--------|-------------|',
      '| Google Gemini | 월 $10-20 상당 |',
      '| Ollama | 완전 물뤂 (로컬) |',
      '| DeepSeek | 물뤂 토큰 제공 |',
      '',
      '## 6. 캐싱',
      '',
      '동일한 요청의 결과를 캐시하여 중복 호출을 방지하세요.',
      '',
      '캐싱 가능한 작업:',
      '- 자주 사용되는 템플릿',
      '- 반복적인 분석',
    ],
    relatedTopics: ['feature-mapping', 'fallback', 'rate-limit'],
  },
];

/**
 * 도움말 주제를 ID로 조회합니다.
 */
export function getHelpTopic(id: string): HelpTopic | undefined {
  return helpContent.find((topic) => topic.id === id);
}

/**
 * 카테고리별 도움말 목록을 반환합니다.
 */
export function getHelpByCategory(category: HelpCategory): HelpTopic[] {
  return helpContent.filter((topic) => topic.category === category);
}

/**
 * 모든 도움말 목록을 반환합니다.
 */
export function getAllHelpTopics(): HelpTopic[] {
  return [...helpContent];
}

/**
 * 도움말을 검색합니다 (제목, 내용).
 */
export function searchHelp(query: string): HelpTopic[] {
  const lowerQuery = query.toLowerCase();
  return helpContent.filter((topic) => {
    const inTitle = topic.title.toLowerCase().includes(lowerQuery);
    const inSummary = topic.summary.toLowerCase().includes(lowerQuery);
    const inContent = Array.isArray(topic.content)
      ? topic.content.some((line) => line.toLowerCase().includes(lowerQuery))
      : topic.content.toLowerCase().includes(lowerQuery);
    return inTitle || inSummary || inContent;
  });
}

/**
 * 관련 주제를 조회합니다.
 */
export function getRelatedTopics(id: string): HelpTopic[] {
  const topic = getHelpTopic(id);
  if (!topic?.relatedTopics) return [];
  return topic.relatedTopics
    .map((relatedId) => getHelpTopic(relatedId))
    .filter((t): t is HelpTopic => t !== undefined);
}

/**
 * 카테고리 목록을 반환합니다.
 */
export function getCategories(): { id: HelpCategory; label: string }[] {
  return [
    { id: 'getting-started', label: '시작하기' },
    { id: 'providers', label: '제공자' },
    { id: 'features', label: '기능' },
    { id: 'troubleshooting', label: '문제해결' },
  ];
}
